/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData apps = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData file_download = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData smartphone = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData mail_outline = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData facebook_circled = const IconData(0xf051, fontFamily: _kFontFam);
  static const IconData twitter_circled = const IconData(0xf057, fontFamily: _kFontFam);
}
