/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Brandico, (C) 2012 by Vitaly Puzrin
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData facebook_circled = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData twitter_circled = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData twitter = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData facebook_1 = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData th_outline = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData th = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData th_1 = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData phone = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData twitter_circled_1 = const IconData(0xf057, fontFamily: _kFontFam);
  static const IconData twitter_1 = const IconData(0xf058, fontFamily: _kFontFam);
  static const IconData gplus_circled = const IconData(0xf059, fontFamily: _kFontFam);
  static const IconData gplus = const IconData(0xf05a, fontFamily: _kFontFam);
  static const IconData facebook = const IconData(0xf09a, fontFamily: _kFontFam);
  static const IconData facebook_official = const IconData(0xf230, fontFamily: _kFontFam);
  static const IconData facebook_rect = const IconData(0xf301, fontFamily: _kFontFam);
  static const IconData facebook_squared = const IconData(0xf308, fontFamily: _kFontFam);
  static const IconData apps = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData file_download = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData smartphone = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData mail_outline = const IconData(0xe803, fontFamily: _kFontFam);
  // static const IconData facebook_circled = const IconData(0xf051, fontFamily: _kFontFam);
  // static const IconData twitter_circled = const IconData(0xf057, fontFamily: _kFontFam);
}
